// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Content.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Content
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.00
// App/Edition: Content/
// User:        2sic Web-Developer
// When:        2024-02-22 12:56:40Z
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for Content
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Content data. <br/>
  /// Generated 2024-02-22 12:56:40Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Image`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Content: ContentAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for Content.
  /// </summary>
  public abstract class ContentAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// Image as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Image")
    /// </summary>
    public string Image => base.Url("Image");

    /// <summary>
    /// Get the file object for Image - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile ImageFile => base.File("ImageFile");

    /// <summary>
    /// Get the folder object for Image.
    /// </summary>
    public IFolder ImageFolder => base.Folder("ImageFolder");

    /// <summary>
    /// Text as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Text", scrubHtml: true) etc.
    /// </summary>
    public string Text => base.String("Text", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    public string Title => base.String("Title", fallback: "");

    /// <summary>
    /// VarShowImage as bool. <br/>
    /// To get nullable use .Get("VarShowImage") as bool?;
    /// </summary>
    public bool VarShowImage => base.Bool("VarShowImage");
  }
}