// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "PresSetMap.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class PresSetMap
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.00
// App/Edition: Content/
// User:        2sic Web-Developer
// When:        2024-02-22 12:56:40Z
namespace AppCode.Data
{
  // This is a generated class for PresSetMap
  // To extend/modify it, see instructions above.

  /// <summary>
  /// PresSetMap data. <br/>
  /// Generated 2024-02-22 12:56:40Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.MapsEnableDirections`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class PresSetMap: PresSetMapAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for PresSetMap.
  /// </summary>
  public abstract class PresSetMapAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// MapsEnableDirections as bool. <br/>
    /// To get nullable use .Get("MapsEnableDirections") as bool?;
    /// </summary>
    public bool MapsEnableDirections => base.Bool("MapsEnableDirections");

    /// <summary>
    /// MapsLabelDirections as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MapsLabelDirections", scrubHtml: true) etc.
    /// </summary>
    public string MapsLabelDirections => base.String("MapsLabelDirections", fallback: "");
  }
}