// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "PresSetText.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class PresSetText
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   DataModelGenerator v17.02.00
// App/Edition: Content/
// User:        2sic Web-Developer
// When:        2024-02-22 12:56:40Z
namespace AppCode.Data
{
  // This is a generated class for PresSetText
  // To extend/modify it, see instructions above.

  /// <summary>
  /// PresSetText data. <br/>
  /// Generated 2024-02-22 12:56:40Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.HeadingType`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class PresSetText: PresSetTextAutoGenerated
  {  }

  /// <summary>
  /// Auto-Generated base class for PresSetText.
  /// </summary>
  public abstract class PresSetTextAutoGenerated: Custom.Data.Item16
  {
    /// <summary>
    /// HeadingType as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("HeadingType", scrubHtml: true) etc.
    /// </summary>
    public string HeadingType => base.String("HeadingType", fallback: "");

    /// <summary>
    /// ImageLightbox as bool. <br/>
    /// To get nullable use .Get("ImageLightbox") as bool?;
    /// </summary>
    public bool ImageLightbox => base.Bool("ImageLightbox");

    /// <summary>
    /// TitleLightbox as bool. <br/>
    /// To get nullable use .Get("TitleLightbox") as bool?;
    /// </summary>
    public bool TitleLightbox => base.Bool("TitleLightbox");
  }
}