namespace ThisApp.Data
{
  /// <summary>
  /// Class to use when working with data of type TextImage.
  /// It has a few special features:
  /// - It's partial, so you can extend it in a different file
  /// - All the automatic/default properties are defined in the base class,
  /// to prevent naming conflicts with your custom properties
  /// and to allow you to override properties as you see fit.
  /// </summary>
  public partial class TextImage : TextImageBaseAutogenerated
  {

  }

  /// <summary>
  /// The autogenerated class for TextImage.
  /// Your code should not use this class directly, but instead use/extend TextImage.
  /// </summary>
  public abstract class TextImageBaseAutogenerated : Custom.Data.Item16
  {
    public string Text => String(fallback: "");

    public string Image => String(fallback: "");

    public string ImageUrl => Url(nameof(Image), fallback: "");
  }

}